//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addre()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int AddresID { get; set; }
        public string AddressType { get; set; }
        public string Addres { get; set; }
        public string City { get; set; }
        public string States { get; set; }
        public string Country { get; set; }
        public string pincode { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
