//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int DetailID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderQuantity { get; set; }
        public Nullable<decimal> IndividualPriceOfProduct { get; set; }
        public Nullable<System.DateTime> OrderDeliveryDate { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
