//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        public int DescriptionID { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string QualityType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
